### ISSUE TITLE
Using the Screenshot button with no World loaded causes the game client to crash to desktop

### ISSUE THREAD

**Issue by jr0dsgarage** [fmbellomy/ScreenshotSettings#3]
## STR:
- Press configured screenshot button while on the Main Menu, before loading a world.

## crash-report
```Java
-- Head --
Thread: Render thread
Stacktrace:
	at com.quantumgarbage.screenshotsettings.util.getters.GameMeta.getWorldNameMultiplayer(GameMeta.java:47)
	at com.quantumgarbage.screenshotsettings.util.getters.GameMeta.getWorldName(GameMeta.java:55)
	at com.quantumgarbage.screenshotsettings.util.FileNameTemplateProcessor.format(FileNameTemplateProcessor.java:17)
	at net.minecraft.class_318.localvar$bmh000$filenameInject(class_318.java:542)
	at net.minecraft.class_318.method_1662(class_318.java)
	at net.minecraft.class_318.method_22690(class_318.java:36)
	at net.minecraft.class_318.method_1659(class_318.java:27)
	at net.minecraft.class_309.method_1466(class_309.java:342)
	at net.minecraft.class_309.method_22678(class_309.java:455)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_309.method_22676(class_309.java:455)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
```

**Comment by fmbellomy** [comment]
Fixed in 2bdea6d
